defaults = { \
'view' : { \
    'finddialog': 'False',
    'statusbar': 'True',
    'toolbar': '(32, 32)',
    'completedtasks': 'True',
    'inactivetasks': 'True',
    'activetasks': 'True',
    'overduetasks': 'True',
    'overbudgettasks': 'True',
    'compositetasks': 'True',
    'startdate': 'True',
    'duedate': 'True',
    'timeleft': 'False',
    'completiondate': 'False',
    'budget': 'False',
    'totalbudget': 'False',
    'timespent': 'False',
    'totaltimespent': 'False',
    'budgetleft': 'False',
    'totalbudgetleft': 'False',
    'priority': 'False',
    'totalpriority': 'False',
    'lastmodificationtime': 'False',
    'totallastmodificationtime': 'False',
    'hourlyfee': 'False',
    'fixedfee': 'False',
    'totalfixedfee': 'False',
    'revenue': 'False',
    'totalrevenue': 'False',
    'alldatecolumns' : 'False',
    'allbudgetcolumns': 'False',
    'allfinancialcolumns': 'False',
    'efforttimespent': 'True',
    'totalefforttimespent': 'True',
    'effortrevenue': 'True',
    'totaleffortrevenue': 'True',
    'tasksdue': 'Unlimited',
    'mainviewer': '0',
    'effortviewer': '0',
    'effortviewerineditor': '0',
    'language': 'en_US',
    'sortby': 'dueDate',
    'sortascending': 'True',
    'sortbystatusfirst': 'True',
    'sortcasesensitive': 'True',
    'tasksearchfilterstring': '',
    'tasksearchfiltermatchcase': 'False' },
'window' : { \
    'size': '(600, 500)',
    'position': '(0, 0)',
    'iconized': 'False',
    'splash': 'True',
    'hidewheniconized': 'True' },
'file' : { \
    'recentfiles': '[]',
    'maxrecentfiles': '4',
    'lastfile': '',
    'autosave': 'False',
    'backup': 'False' },
'color' : { \
    'activetasks': '(0, 0, 0)',
    'completedtasks': '(0, 255, 0)',
    'overduetasks': '(255, 0, 0)',
    'inactivetasks': '(192, 192, 192)',
    'duetodaytasks': '(255, 128, 0)'}}

