defaults = { \
'view' : { \
    'finddialog' : 'False',
    'statusbar' : 'True',
    'toolbar' : '(32, 32)',
    'completedtasks' : 'True',
    'inactivetasks' : 'True',
    'activetasks' : 'True',
    'overduetasks' : 'True',
    'overbudgettasks' : 'True',
    'compositetasks' : 'True',
    'startdate' : 'True',
    'duedate' : 'True',
    'daysleft' : 'False',
    'completiondate' : 'False',
    'budget' : 'False',
    'totalbudget' : 'False',
    'timespent' : 'False',
    'totaltimespent' : 'False',
    'budgetleft' : 'False',
    'totalbudgetleft' : 'False',
    'tasksdue' : 'Unlimited',
    'mainviewer' : 'Task list',
    'effortviewer' : 'Effort list',
    'effortviewerineditor' : 'Effort list',
    'language' : 'en_US',
    'sort': 'False' },
'window' : { \
    'size' : '(600, 500)',
    'position' : '(0, 0)',
    'iconized' : 'False',
    'splash' : 'True' },
'file' : { \
    'lastfile' : '',
    'autosave' : 'False',
    'backup' : 'False' }}

